(class (attrs ) org/python/modules/SynchronizedCallable
 (super org/python/core/PyObject)
 (source "synchronize.java")

 (field (attrs ) callable [object org/python/core/PyObject] )

(method (attrs public ) <init>([object org/python/core/PyObject] )void
  (limit registers 2)
  ; this: v0 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v1 ([object org/python/core/PyObject])
  (line 9)
  (invoke-direct {v0} org/python/core/PyObject/<init> )
  (line 10)
  (iput-object v1 v0 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (line 11)
  (return-void )
 )

(method (attrs public ) __call__()[object org/python/core/PyObject]
  (limit registers 2)
  ; this: v1 ([object org/python/modules/SynchronizedCallable])
  (line 19)
  (const-string v0 "synchronized callable called with 0 args")
  (invoke-static {v0} org/python/core/Py/TypeError [object java/lang/String] )
  (move-result-object v0)
  (throw v0)
)

(method (attrs public ) __call__([object org/python/core/PyObject] )[object org/python/core/PyObject]
  (limit registers 4)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([object org/python/core/PyObject])
  (catchall  java/lang/Exception from la1cd2 to la1ce6 using la1ce2)
  (line 23)
  (invoke-static {v3} org/python/modules/synchronize/_getSync [object org/python/core/PyObject] )
  (move-result-object v1)
  (monitor-enter v1)
  (label la1cd2)
  (line 24)
  (iget-object v0 v2 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (invoke-virtual {v0 v3} org/python/core/PyObject/__call__ [object org/python/core/PyObject] )
  (move-result-object v0)
  (monitor-exit v1)
  (return-object v0)
  (label la1ce2)
  (line 23)
  (move-exception v0)
  (monitor-exit v1)
  (label la1ce6)
  (throw v0)
)

(method (attrs public ) __call__([object org/python/core/PyObject] [object org/python/core/PyObject] )[object org/python/core/PyObject]
  (limit registers 5)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([object org/python/core/PyObject])
  ; parameter[1] : v4 ([object org/python/core/PyObject])
  (catchall  java/lang/Exception from la1d0e to la1d22 using la1d1e)
  (line 29)
  (invoke-static {v3} org/python/modules/synchronize/_getSync [object org/python/core/PyObject] )
  (move-result-object v1)
  (monitor-enter v1)
  (label la1d0e)
  (line 30)
  (iget-object v0 v2 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (invoke-virtual {v0 v3 v4} org/python/core/PyObject/__call__ [object org/python/core/PyObject] [object org/python/core/PyObject] )
  (move-result-object v0)
  (monitor-exit v1)
  (return-object v0)
  (label la1d1e)
  (line 29)
  (move-exception v0)
  (monitor-exit v1)
  (label la1d22)
  (throw v0)
)

(method (attrs public ) __call__([object org/python/core/PyObject] [object org/python/core/PyObject] [object org/python/core/PyObject] )[object org/python/core/PyObject]
  (limit registers 6)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([object org/python/core/PyObject])
  ; parameter[1] : v4 ([object org/python/core/PyObject])
  ; parameter[2] : v5 ([object org/python/core/PyObject])
  (catchall  java/lang/Exception from la1d4a to la1d5e using la1d5a)
  (line 35)
  (invoke-static {v3} org/python/modules/synchronize/_getSync [object org/python/core/PyObject] )
  (move-result-object v1)
  (monitor-enter v1)
  (label la1d4a)
  (line 36)
  (iget-object v0 v2 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (invoke-virtual {v0 v3 v4 v5} org/python/core/PyObject/__call__ [object org/python/core/PyObject] [object org/python/core/PyObject] [object org/python/core/PyObject] )
  (move-result-object v0)
  (monitor-exit v1)
  (return-object v0)
  (label la1d5a)
  (line 35)
  (move-exception v0)
  (monitor-exit v1)
  (label la1d5e)
  (throw v0)
)

(method (attrs public ) __call__([object org/python/core/PyObject] [array [object org/python/core/PyObject]] [array [object java/lang/String]] )[object org/python/core/PyObject]
  (limit registers 6)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([object org/python/core/PyObject])
  ; parameter[1] : v4 ([array [object org/python/core/PyObject]])
  ; parameter[2] : v5 ([array [object java/lang/String]])
  (catchall  java/lang/Exception from la1d86 to la1d9a using la1d96)
  (line 52)
  (invoke-static {v3} org/python/modules/synchronize/_getSync [object org/python/core/PyObject] )
  (move-result-object v1)
  (monitor-enter v1)
  (label la1d86)
  (line 53)
  (iget-object v0 v2 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (invoke-virtual {v0 v3 v4 v5} org/python/core/PyObject/__call__ [object org/python/core/PyObject] [array [object org/python/core/PyObject]] [array [object java/lang/String]] )
  (move-result-object v0)
  (monitor-exit v1)
  (return-object v0)
  (label la1d96)
  (line 52)
  (move-exception v0)
  (monitor-exit v1)
  (label la1d9a)
  (throw v0)
)

(method (attrs public ) __call__([array [object org/python/core/PyObject]] [array [object java/lang/String]] )[object org/python/core/PyObject]
  (limit registers 5)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([array [object org/python/core/PyObject]])
  ; parameter[1] : v4 ([array [object java/lang/String]])
  (catchall  java/lang/Exception from la1ddc to la1df0 using la1dec)
  (line 41)
  (array-length v0 v3)
  (if-nez v0 la1dcc)
  (line 42)
  (const-string v0 "synchronized callable called with 0 args")
  (invoke-static {v0} org/python/core/Py/TypeError [object java/lang/String] )
  (move-result-object v0)
  (throw v0)
  (label la1dcc)
  (line 44)
  (const/4 v0 0)
  (aget-object v0 v3 v0)
  (invoke-static {v0} org/python/modules/synchronize/_getSync [object org/python/core/PyObject] )
  (move-result-object v1)
  (monitor-enter v1)
  (label la1ddc)
  (line 45)
  (iget-object v0 v2 org/python/modules/SynchronizedCallable.callable [object org/python/core/PyObject])
  (invoke-virtual {v0 v3 v4} org/python/core/PyObject/__call__ [array [object org/python/core/PyObject]] [array [object java/lang/String]] )
  (move-result-object v0)
  (monitor-exit v1)
  (return-object v0)
  (label la1dec)
  (line 44)
  (move-exception v0)
  (monitor-exit v1)
  (label la1df0)
  (throw v0)
)

(method (attrs public ) _doget([object org/python/core/PyObject] )[object org/python/core/PyObject]
  (limit registers 4)
  ; this: v2 ([object org/python/modules/SynchronizedCallable])
  ; parameter[0] : v3 ([object org/python/core/PyObject])
  (line 15)
  (new-instance v0 org/python/core/PyMethod)
  (const/4 v1 0)
  (invoke-direct {v0 v3 v2 v1} org/python/core/PyMethod/<init> [object org/python/core/PyObject] [object org/python/core/PyObject] [object org/python/core/PyObject] )
  (return-object v0)
)

)
